-- USER SQL
CREATE USER "DEV_SENHA_ATENDIMENTO" IDENTIFIED BY "12345"  ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_MONITOR" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "CTXAPP" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_AUDIT_CLEANUP" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_ALL" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "OLAP_USER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "OLAP_XS_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_SECANALYST" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XS_CACHE_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "GDS_CATALOG_SELECT" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "PROVISIONER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "AUDIT_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_REALM_RESOURCE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "SYSUMF_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "APPLICATION_TRACE_VIEWER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_PUBLIC" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "LBAC_DBA" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "OPTIMIZER_PROCESSING_RATE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_USER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "GSMUSER_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DBJAVASCRIPT" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "GSM_POOLADMIN_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_POLICY_OWNER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XS_SESSION_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_GOLDENGATE_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_XSTREAM_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_PATCH_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "GGSYS_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "JMXSERVER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "CONNECT" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "SODA_APP" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "GSMADMIN_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "PDB_DBA" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "RDFCTX_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "CDB_DBA" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "AUDIT_VIEWER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_OWNER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DATAPATCH_ROLE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_ACCTMGR" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_REALM_OWNER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DBMS_MDX_INTERNAL" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "DV_STREAMS_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XS_NAMESPACE_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "ORDADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "CAPTURE_ADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XS_CONNECT" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "XDBADMIN" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_BASIC" TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY ANALYTIC VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY SQL TRANSLATION PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT MANAGE ANY FILE GROUP TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER PUBLIC DATABASE LINK TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT MANAGE FILE GROUP TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT INHERIT ANY PRIVILEGES TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT KEEP SYSGUID TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ASSEMBLY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY LIBRARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY EDITION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ROLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE LIBRARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ROLLBACK SEGMENT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADMINISTER DATABASE TRIGGER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY OUTLINE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY ANALYTIC VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY INDEXTYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT USE ANY JOB RESOURCE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY DIRECTORY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY RULE SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT USE ANY SQL TRANSLATION PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY MINING MODEL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DEBUG CONNECT SESSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT LOGMINING TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY ATTRIBUTE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY MINING MODEL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE LOCKDOWN PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER SESSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE PLUGGABLE DATABASE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY ANALYTIC VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT WRITE ANY ANALYTIC VIEW CACHE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT MERGE ANY VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT READ ANY ANALYTIC VIEW CACHE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE SQL TRANSLATION PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY MATERIALIZED VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT AUDIT SYSTEM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE OPERATOR TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT MANAGE ANY QUEUE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY SQL PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT GRANT ANY OBJECT PRIVILEGE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE INDEXTYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT AUDIT ANY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT INHERIT ANY REMOTE PRIVILEGES TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SYSKM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DEBUG ANY PROCEDURE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE BUILD PROCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER DATABASE LINK TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY ASSEMBLY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY EVALUATION CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY MINING MODEL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SYSRAC TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DELETE ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE RULE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT BECOME USER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE BUILD PROCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT INSERT ANY MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY SQL PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT FORCE ANY TRANSACTION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY EDITION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EM EXPRESS CONNECT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY MATERIALIZED VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE BUILD PROCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY RULE SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT BACKUP ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE CREDENTIAL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY LIBRARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY OUTLINE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ASSEMBLY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY HIERARCHY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANALYTIC VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADMINISTER KEY MANAGEMENT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY CLUSTER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY CLASS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE BUILD PROCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY CREDENTIAL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SYSBACKUP TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY RULE SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UNDER ANY TYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT MANAGE TABLESPACE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY OPERATOR TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY OPERATOR TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY HIERARCHY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXEMPT IDENTITY POLICY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE TYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DELETE ANY MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT LOCK ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE EVALUATION CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY TYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADVISOR TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE PUBLIC DATABASE LINK TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ANALYZE ANY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ATTRIBUTE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY RULE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT INSERT ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ROLLBACK SEGMENT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY JOB TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER USER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT QUERY REWRITE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT GLOBAL QUERY REWRITE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY CLUSTER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY RULE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SYSDBA TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADMINISTER RESOURCE MANAGER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY MINING MODEL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SET CONTAINER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROGRAM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXEMPT REDACTION POLICY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY TYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ON COMMIT REFRESH TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DEBUG CONNECT ANY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE HIERARCHY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT COMMENT ANY MINING MODEL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADMINISTER SQL TUNING SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SYSOPER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY INDEXTYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT KEEP DATE TIME TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT RESTRICTED SESSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SYSDG TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DEQUEUE ANY QUEUE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ANALYZE ANY DICTIONARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY INDEXTYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT TRANSLATE ANY SQL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADMINISTER ANY SQL TUNING SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE USER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY OPERATOR TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE CUBE BUILD PROCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY LIBRARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY CLUSTER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER TABLESPACE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UNDER ANY VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY ASSEMBLY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER LOCKDOWN PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXPORT FULL DATABASE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY MEASURE FOLDER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY EVALUATION CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT TEXT DATASTORE ACCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT FLASHBACK ARCHIVE ADMINISTER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT IMPORT FULL DATABASE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY OUTLINE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT READ ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP USER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CHANGE NOTIFICATION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE MINING MODEL TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP LOCKDOWN PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE RULE SET TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXEMPT ACCESS POLICY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT MANAGE SCHEDULER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT READ ANY FILE GROUP TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT FORCE TRANSACTION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY CUBE BUILD PROCESS TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP PUBLIC DATABASE LINK TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY INDEXTYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY SQL PROFILE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER SYSTEM TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY CUBE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY ASSEMBLY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ENQUEUE ANY QUEUE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY EVALUATION CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY ASSEMBLY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY TYPE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT REDEFINE ANY TABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE CLUSTER TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT EXECUTE ANY EVALUATION CONTEXT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT RESUMABLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY LIBRARY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER DATABASE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY RULE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY OPERATOR TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT CREATE CUBE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER RESOURCE COST TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ANY HIERARCHY TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT DROP TABLESPACE TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT ALTER ROLLBACK SEGMENT TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;
GRANT PURGE DBA_RECYCLEBIN TO "DEV_SENHA_ATENDIMENTO" WITH ADMIN OPTION;


CREATE SEQUENCE seq_senha;

CREATE TABLE tb_senha(
    id_senha NUMBER,
    prioridade NUMBER NOT NULL,
    status NUMBER NOT NULL,
    CONSTRAINT id_senha_pk PRIMARY KEY(id_senha)
);

ALTER TABLE tb_senha
ADD horario DATE DEFAULT SYSTIMESTAMP;

CREATE TABLE tb_guiche(
    id_guiche NUMBER,
    CONSTRAINT id_guiche_pk PRIMARY KEY(id_guiche)
);

CREATE SEQUENCE seq_atendimento;

CREATE TABLE tb_atendimento(
    id_atendimento NUMBER,
    id_senha NUMBER NOT NULL,
    id_guiche NUMBER NOT NULL,
    CONSTRAINT id_atendimento_pk PRIMARY KEY(id_atendimento),
    CONSTRAINT atendimento_senha_fk FOREIGN KEY(id_senha) REFERENCES tb_senha(id_senha),
    CONSTRAINT atendimento_guiche_fk FOREIGN KEY(id_guiche) REFERENCES tb_guiche(id_guiche)
);


ALTER TABLE tb_atendimento
ADD CONSTRAINT id_senha_un UNIQUE(id_senha);


ALTER TABLE tb_atendimento
ADD horario DATE DEFAULT SYSTIMESTAMP;


create or replace FUNCTION func_chama_senha(pPrioridade IN NUMBER)
    RETURN NUMBER
IS
    vId         NUMBER;
BEGIN
    SELECT *
    INTO vId
    FROM (  SELECT id_senha
            FROM tb_senha
            WHERE prioridade = 2
            AND status = 1
            ORDER BY id_senha ASC)
    WHERE ROWNUM = 1;

    RETURN vId;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;


create or replace PROCEDURE proc_resetar_seq_atendimento
IS
    vNum        NUMBER;
BEGIN

    vNum := seq_atendimento.NEXTVAL;

    EXECUTE IMMEDIATE
    'ALTER SEQUENCE seq_atendimento INCREMENT BY -' || vNum || ' MINVALUE 0';

    vNum := seq_atendimento.NEXTVAL;

    EXECUTE IMMEDIATE
    'ALTER SEQUENCE seq_atendimento INCREMENT BY 1 MINVALUE 0';

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO ORACLE ' || SQLCODE || SQLERRM);

END;

create or replace PROCEDURE proc_resetar_seq_senha
IS
    vNum        NUMBER;
BEGIN

    vNum := seq_senha.NEXTVAL;

    EXECUTE IMMEDIATE
    'ALTER SEQUENCE seq_senha INCREMENT BY -' || vNum || ' MINVALUE 0';

    vNum := seq_senha.NEXTVAL;

    EXECUTE IMMEDIATE
    'ALTER SEQUENCE seq_senha INCREMENT BY 1 MINVALUE 0';

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO ORACLE ' || SQLCODE || SQLERRM);

END;

create or replace PROCEDURE proc_resetar_sequences
IS
    vNum        NUMBER;
BEGIN

    proc_resetar_seq_atendimento;
    proc_resetar_seq_senha;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO ORACLE ' || SQLCODE || SQLERRM);

END;

create or replace PROCEDURE proc_resetar_senha_atendimento
IS
BEGIN
    DELETE
    FROM tb_atendimento;

    DELETE 
    FROM tb_senha;

    proc_resetar_sequences;
END;